[build]
  base = "front"  # Set to 'front' because the frontend code is in that directory
  publish = "front/dist"  # The path to your build output folder
  command = "npm install && npm run build"  # The build command for your frontend

[functions]
  directory = "back/netlify/functions"  # Path to your serverless functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
