[build]
  base = "front"  # Set to 'front' because the frontend code is in that directory
  publish = "front/build"  # This is where Netlify will deploy the frontend
  command = "npm install && npm run build"  # Build command for frontend

[functions]
  directory = "back/netlify/functions"  # Path to your serverless functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
