[build]
  base = "teacher_routine/front"  # The base directory for the frontend code
  publish = "teacher_routine/front/dist"  # The directory where Vite will output the production build
  command = "npm install && npm run build"  # The command to build your Vite app

[functions]
  directory = "teacher_routine/back/netlify/functions"  # Directory for serverless functions (backend)

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"  # This points to the serverless function endpoint
  status = 200
