[build]
  command = "chmod +x ./netlify-build.sh && ./netlify-build.sh"
  publish = "dist"
  base = "teacher_routine/front"

[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
